server {
    listen 80;
    server_name __SERVER_NAME__;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name __SERVER_NAME__;

    ssl_certificate     __CERT_FILE__;
    ssl_certificate_key __KEY_FILE__;

    root /var/www/study-sim/__DOC_ROOT__;
    index index.html;

    access_log /var/log/nginx/__LOG_NAME__.access.log;
    error_log  /var/log/nginx/__LOG_NAME__.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
